language: node_js
node_js:
  - "10"
before_script:
  - npm run build
before_deploy:
  - git config --local user.name "William Wong"
  - git config --local user.email "compulim@hotmail.com"
  - npx version-from-git --travis
deploy:
  - provider: npm
    api_key:
      secure: "Z8hkT5qzmMTmi53K7q47n2jAv/af84tMRBA0jwzLpfMVgwHF2qKU7BMbWMldgtGkga22oGf7BLolwXFLrp0G43tW7g5j/25zpPijxJudHk3u4FUPM9/6Y0JbRSze1bfGP7U3fqJtYwHo9duYfzn1xysPc2T5/ZMY2aIzCBvDG4eyJj4QdknGFtaOOZE6Ah2pkF3DgcQG3qmgrTUAu56Z6+w7xqyAm5A6G+FlJkwMRtzmKGjeVfQQjTLpHbQaSheAztHGQPqUUcSUVK+xnJrzBb5FY5iK2dmbyGWiv7EtaUFJhBjN3GYDxQVmFgurl50ITxHABqhcYbW8uhsiy12YKM1VlPyGcFrYSE2X8jFYdCqNzq7ZS6xvDaVnaDKpmeLsY5rxQCPj42T8ih4xRWoIC1YZ5CoAWayeEnm2NeP7+k2zT5VMWZYpw/LRQ1rmkw+sWuTI9u5UyvmT2FWTbia4/um8+lGuqRKy7pBWXHcGkKf0LSXVkR/5wHKsEzWiAM3PvTGvHTVP7oF+6CkcE7Wqi7O0NoMoFYD2OcEsyLC3wts1PulRwxOYixymfIEoRKsL2OuGeFSeuz/hFH2JmdAGRLwH2dEW3Bv7oUlxrlLywtdXLbhqViX4shkyLmvb+y2llZbeYMszpPFZtWIxxXGiQ1SQIbK+oeLUjoqoH2gUYLY="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "Z8hkT5qzmMTmi53K7q47n2jAv/af84tMRBA0jwzLpfMVgwHF2qKU7BMbWMldgtGkga22oGf7BLolwXFLrp0G43tW7g5j/25zpPijxJudHk3u4FUPM9/6Y0JbRSze1bfGP7U3fqJtYwHo9duYfzn1xysPc2T5/ZMY2aIzCBvDG4eyJj4QdknGFtaOOZE6Ah2pkF3DgcQG3qmgrTUAu56Z6+w7xqyAm5A6G+FlJkwMRtzmKGjeVfQQjTLpHbQaSheAztHGQPqUUcSUVK+xnJrzBb5FY5iK2dmbyGWiv7EtaUFJhBjN3GYDxQVmFgurl50ITxHABqhcYbW8uhsiy12YKM1VlPyGcFrYSE2X8jFYdCqNzq7ZS6xvDaVnaDKpmeLsY5rxQCPj42T8ih4xRWoIC1YZ5CoAWayeEnm2NeP7+k2zT5VMWZYpw/LRQ1rmkw+sWuTI9u5UyvmT2FWTbia4/um8+lGuqRKy7pBWXHcGkKf0LSXVkR/5wHKsEzWiAM3PvTGvHTVP7oF+6CkcE7Wqi7O0NoMoFYD2OcEsyLC3wts1PulRwxOYixymfIEoRKsL2OuGeFSeuz/hFH2JmdAGRLwH2dEW3Bv7oUlxrlLywtdXLbhqViX4shkyLmvb+y2llZbeYMszpPFZtWIxxXGiQ1SQIbK+oeLUjoqoH2gUYLY="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: "ssdQMYSzYYGE4/rK3nVnH91GA6Ur9wau10GE+YI6r2thOKsdIUS1zIHHha06ujhzEbDZOEzWgjNmYXz/TecEpVnQ8wO9sFIYKhUumMzn7kxJOUy9SWPMJxUITUsyc6F9j6IGZA8RHfYLKk6hyAzng3WkWrLbauUSsrhjs1b6KPy/9gcYyFcWDV+GTteVFKlkkaDA74U6uzdAhP1GVMv3YZqdWnXNNHCYqwIzE9Ktbw8FbFo0KtYHOsJ/RYaXnPpoFGQZ6p3AoW2Jez+lGU1G1tO8uSjKPhGS3OH+MX3DuKPfzXHNncCL0zd9NPiJC7wkNvUximOPX0prd5cIApHoEXwisykx3QhDV9EfMg1UmSef6XSFhluWOC5WadDSKaa/RLsobbZjGmbHwPNZOpjH7jStYOkRz1lA4YT7OM6TtctdtR39/tlUYVXxGLqg9VEMl1zObGpkv/BxfGjuYP/wzhiBlE2rfGBDLPKCN2jhZOotGRfwSeDUPvlOmkQJZBFGV4Us0UE68On1hN33nwbpw+RY0KSNmzzmVvafwpLxsw4HaNGgYt7yGPxbKhFKZp1OUnUeMa6uUEpIfY8APKq6pq4GO1T8cEgHFWkUwsL8mW0zCd2KcIuRu0WAn1Vea28d560M4Ekq1WVNB4b/ewbnzjgeNrwOPwOOOd9pod3fhKM="
    on:
      tags: true
    skip_cleanup: true
